# Generated by Django 5.2.8 on 2025-12-28 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0016_servicecatalog_active_servicecatalog_base_price'),
        ('recommender', '0005_remove_pestrecommendation_responded_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=20)),
                ('recipient', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('provider', models.CharField(default='rapbooster', max_length=50)),
                ('provider_message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('provider_status', models.CharField(max_length=50)),
                ('raw_response', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmapp.customer_details')),
                ('recommendation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recommender.pestrecommendation')),
            ],
            options={
                'db_table': 'message_delivery_log',
                'indexes': [models.Index(fields=['customer', 'channel'], name='message_del_custome_cf0671_idx'), models.Index(fields=['provider_message_id'], name='message_del_provide_d950ec_idx')],
            },
        ),
    ]
