# Generated by Django 5.2.8 on 2025-12-29 06:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0016_servicecatalog_active_servicecatalog_base_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentmessagelog',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
