# Generated by Django 5.2.8 on 2025-12-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0017_sentmessagelog_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentmessagelog',
            name='delivery_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sentmessagelog',
            name='delivery_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sentmessagelog',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sentmessagelog',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sentmessagelog',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed'), ('error', 'Error')], default='queued', max_length=20),
        ),
    ]
