# Generated by Django 5.2.8 on 2026-01-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0018_sentmessagelog_delivery_payload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentmessagelog',
            name='delivery_status',
            field=models.CharField(blank=True, choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('opened', 'Opened'), ('failed', 'Failed'), ('error', 'Error')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sentmessagelog',
            name='rendered_subject',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sentmessagelog',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('opened', 'Opened'), ('failed', 'Failed'), ('error', 'Error')], default='queued', max_length=20),
        ),
    ]
