# Generated by Django 5.2.8 on 2026-01-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0019_alter_sentmessagelog_delivery_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecatalog',
            name='is_recommendable',
            field=models.BooleanField(default=True),
        ),
    ]
